### ISSUE TITLE
Smartermail Alias Project

### ISSUE THREAD

**Issue by PrecisionDoor** [PrecisionDoor/Support-Project--PHP-#1117]
I need to get a list of all aliases and their emails that they are forwarding to so we can sort though them and see which ones are used mostly by corporate and/or are important for lead generation.   Can you work on figuring out how to export that list?  If not exportable, there is likely a way to get it off the server direclty.  See what you can find out... 

We're going to be moving these into Neighborly's email account.  There are too many emails not being delivered because of our email server's reputation.  It only seems to happen with these alises which is why I want to focus on this first.

**Comment by PrecisionDoor** [comment]
@AnthonyVeronesi I think I read of ways to export the list within the UI and not need to develop a script or use the API.  Can you spend more time on this, maybe look closer at the reports section?

**Comment by PrecisionDoor** [comment]
@AnthonyVeronesi Bumping

**Comment by PrecisionDoor** [comment]
@AnthonyVeronesi I think I read of ways to export the list within the UI and not need to develop a script or use the API. Can you spend more time on this, maybe look closer at the reports section?

**Comment by PrecisionDoor** [comment]
Dang, Okay... I'll just have to figure the API out then.

**Comment by AnthonyVeronesi** [comment]
The issue with that, is that it looks like you can't just download a CSV.... it still looks like it's a one by one process

**Comment by PrecisionDoor** [comment]
@AnthonyVeronesi I've figured out how to automate this except I need the full list of aliases so I can iterate down it.  The API requires me to provide at least that input in the parameters... can you just go through these 17 pagres and copy/paste the values in to a speradsheet for me?

![image](https://user-images.githubusercontent.com/765730/230677888-d99079fc-653e-499c-a0f3-32342790bdd3.png)
![image](https://user-images.githubusercontent.com/765730/230677920-08f336db-3611-4502-b441-4567c7606311.png)

**Comment by AnthonyVeronesi** [comment]
[smartermail alias project.xlsx](https://github.com/PrecisionDoor/Support-Project--PHP-/files/11190787/smartermail.alias.project.xlsx)

**Comment by PrecisionDoor** [comment]
request submitted to NBLY IT.
[PDS Corporate Alises.xlsx](https://github.com/PrecisionDoor/Support-Project--PHP-/files/11193916/PDS.Corporate.Alises.xlsx)
