### ISSUE TITLE
Sales Conversion Report Question

### ISSUE THREAD

**Issue by PrecisionDoor** [PrecisionDoor/Support-Project--PHP-#1461]
![image](https://user-images.githubusercontent.com/765730/222209061-23c5efef-22bb-4af0-9657-8700a0c98980.png)

**Comment by PrecisionDoor** [comment]
#1459

**Comment by PrecisionDoor** [comment]
@AnthonyVeronesi See what you can find out for me to answer Jon's questions, please.

**Comment by AnthonyVeronesi** [comment]
Closed Sales Leads are workorders in which an estimate was created but not sold... Total Sales are sold estimates in any part of the process(sales order or invoice, paid or unpaid)

**Comment by AnthonyVeronesi** [comment]
@PrecisionDoor Can I close this one?

**Comment by PrecisionDoor** [comment]
No, I don't think your explanation is correct.  I've been meaning to look at myself.

**Comment by PrecisionDoor** [comment]
report has been explained to Jon
