### ISSUE TITLE
ST Pricebook Exports

### ISSUE THREAD

**Issue by PrecisionDoor** [PrecisionDoor/Support-Project--PHP-#1600]
@AnthonyVeronesi I need you to go into all the active markets in Service Titan, export their Pricebooks to Excel and save each as "<Market Name> Pricebook".   You can export by going to Pricebook -> Import/Export,  tab to export and choose Pricebook

**Comment by PrecisionDoor** [comment]
@AnthonyVeronesi Hold off on this for now. Still in the planning phase.

**Comment by AnthonyVeronesi** [comment]
This was completed and sent via teams
[Pricebook Data.zip](https://github.com/PrecisionDoor/Support-Project--PHP-/files/11044668/Pricebook.Data.zip)
