### ISSUE TITLE
Balance Due Test

### ISSUE THREAD

**Issue by PrecisionDoor** [PrecisionDoor/Support-Project--PHP-#1608]
branch name: 128981-balance-due-scripts

Steps to executes balance_due_test scripts

Login to apps
1.	got to path app/nova_opal/current
2.	bundle exec rails c -e production/staging (if its staging type staging else production, it will open rails console, in console type below method)
3.	Invoice.update_invoices(location_id: 2, year_month: "2022-02")
4.	You can replace 2 with any location id with and year_month with "2022-02", you can pass as YYYY-MM
5.	Anyone of  two arguments is required, either pass location_id or year_month or both.

**Comment by AnthonyVeronesi** [comment]
Tested over staging, everything looks right. The only thing I've noticed is that some of the once with a "0" balance show as Null in the test column. I've looked at individual examples and can't seem to find a reason why.

![image](https://user-images.githubusercontent.com/24830254/227332271-2a5eff45-ade2-4aa0-b160-09ea62b1ed11.png)
