### ISSUE TITLE
Update Brian Tindall - Portal

### ISSUE THREAD

**Issue by PrecisionDoor** [PrecisionDoor/Support-Project--PHP-#1613]
[3:48 PM] Michael Brickner
When you get time, can you assign PDS of Central MD to Brian Tindall in the OPAL Sales Portal...effective 12/01/2020.  Currently assigned to Corp Store.  Thx

![image](https://user-images.githubusercontent.com/765730/227335086-fedf3b99-1a65-4f0f-aaa7-4eb902b2e4f1.png)

**Comment by AnthonyVeronesi** [comment]
![image](https://user-images.githubusercontent.com/24830254/227580527-71ae02a8-1407-4f4e-afb8-ab0703e4e4ac.png)
