### ISSUE TITLE
OM3.5.1 - "Final" UAT Testing

### ISSUE THREAD

**Issue by PrecisionDoor** [PrecisionDoor/Support-Project--PHP-#1626]
downloadn and install this APK:

https://frantech-my.sharepoint.com/:u:/g/personal/david_stanifer_dwyergroup_com/EXb0PamVHKxOr_QIBjN-i_UB2KC-5ksqIIKa5GHxXu1fWQ?e=7tO5eg

Do general testing for now, I can provide a list of specifics to test in a bit.

**Comment by AnthonyVeronesi** [comment]
Everything is tested and seems to work. I do see some issues with the safety inspection, though. The issue with the back button is still there, which is fine if not a little bit janky. But further with that particular issue, when you hit the back arrow it will prompt you to confirm or cancel. If you cancel, it will return you to the last note you were trying. If you select confirm(meaning you realize that it will not save, and you want to back out anyways) nothing happens. It behaves in a way that one would assume the cancel button would(bringing you directly back to where you were previous to hitting the arrow).

The other issue is this bug fix...

https://dwyergroup.visualstudio.com/Main/_workitems/edit/139705

I'm not sure what they are talking about. Are they saying that when you enter custom notes, and then change it to a dropdown note that the custom notes should save in the even that it is changed back? It's not clear to me.

**Comment by PrecisionDoor** [comment]
I wouldn't worry about it.  Good enough for me. Thanks for testing
