### ISSUE TITLE
Credit Card Number Search

### ISSUE THREAD

**Issue by PrecisionDoor** [PrecisionDoor/Support-Project--PHP-#1765]
Can you do a search under the memo / note section of payments to see if there are any full 10 digit credit card numbers recorded in them?  If you can check customer notes and/or other free form typing places like safety inspections that's be good.  We need to do this for PCI compliance check.

Thanks

**Comment by PrecisionDoor** [comment]
@AnthonyVeronesi 

Get me a list of payment ids that look like credit card numbers.

SELECT id,check_cc_auth_number FROM nova_opal.payments
where length(check_cc_auth_number) > 16;

**Comment by AnthonyVeronesi** [comment]
[cc list.csv](https://github.com/PrecisionDoor/Support-Project--PHP-/files/11275581/cc.list.csv)
