### ISSUE TITLE
Test CC - Open Invoice Issue

### ISSUE THREAD

**Issue by PrecisionDoor** [PrecisionDoor/Support-Project--PHP-#1780]
Can you test this APK and see if it's doing the same problem with credit card payments (manual) not closing the invoice.  I knew they fixed this, here is the user story from last november on it.

https://dwyergroup.visualstudio.com/Main/_workitems/edit/122630

**UPDATE-New APK will be coming shortly.  Please stand by**

**Comment by AnthonyVeronesi** [comment]
Unable to fully test in staging

**Comment by PrecisionDoor** [comment]
I think I know why this isn't working

**Comment by AnthonyVeronesi** [comment]
Tested and works
